illumail/api/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers


urlpatterns = [
    path('api/courses/', CoursesViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('api/courses/<int:pk>/', CoursesViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),

    path('api/users/<int:pk>/my_profile/', MyProfileAPI.as_view()),
    path('api/users/create/', UserAPICreate.as_view()),

    path('api/auth/', include('rest_framework.urls')),
]

illumail/illumail/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat/", include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('', include('users.urls')),
    path('', include('courses.urls')),
    path('', include('study_groups.urls')),
    path('', include('payments.urls')),
    path('', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

illumail/users/urls.py
from django.contrib import admin
from django.urls import path
from .views import *


urlpatterns = [
    path('register/', RegisterNewUser.as_view(), name='register_user'),
    path('login/', LoginUser.as_view(), name='login_user'),
    path('logout/', LogoutUser.as_view(), name='logout_user'),
    path('my_profile/<int:id>/', MyProfile.as_view(), name='my_profile'),
    path('my_profile/<int:id>/edit/', UpdateProfile.as_view(), name='update_profile'),
    path('my_profile/<int:pk>/edit/password/', NewPassword.as_view(), name='new_password'),
    path('my_profile/<int:pk>/subscriptions/', MySubscriptions.as_view(), name='my_subscriptions'),
    path('user/<int:pk>/', AnotherUser.as_view(), name='another_user'),
    path('user/<int:pk>/add_subscription/', add_subscription, name='add_subscription'),
    path('user/<int:pk>/unsubscribe/', unsubscribe, name='unsubscribe'),
    path('search_users/', SearchUsers.as_view(), name='search_users'),
]

illumail/users/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class CustomUser(AbstractUser):
    photo = models.ImageField(upload_to='avatars/%Y/%m/%d', verbose_name='Фото', default='avatar.png')
    bio = models.CharField(max_length=200, verbose_name='О себе', blank=True)
    patronymic = models.CharField(max_length=300, verbose_name='Отчество')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    user_courses = models.ManyToManyField('courses.Courses', blank=True, verbose_name='Курсы')
    subscriptions = models.ManyToManyField("CustomUser", blank=True, verbose_name='Подписки')
    user_groups = models.ManyToManyField('study_groups.StudyGroup', blank=True, verbose_name='Учебные группы')

    def users_courses(self):
        return [c.title for c in self.user_courses.all()]

    # def users_subscriptions(self):
    #     return [s.username for s in self.subscriptions.all()]

    def get_absolute_url(self):
        return reverse('my_profile', kwargs={'id': self.id})

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

illumail/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import get_user_model


class RegisterUser(UserCreationForm):
    first_name = forms.CharField(label='Имя:', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(label='Фамилия:', required=True, widget=forms.TextInput(attrs={
        'class': 'form-control'}))
    patronymic = forms.CharField(label='Отчество:', required=True, widget=forms.TextInput(attrs={
        'class': 'form-control'}))
    email = forms.EmailField(label='Эл.почта:', required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(label='Имя пользователя:', required=True, widget=forms.TextInput(attrs={
        'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль:', required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control'}))
    password2 = forms.CharField(label='Подтверждение пароля:', required=True, widget=forms.PasswordInput(attrs={
        'class': 'form-control'}))

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'patronymic', 'email', 'username', 'password1', 'password2')


class UpdateProfileForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    patronymic = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    bio = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'О себе...'}))

    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'patronymic', 'photo', 'email', 'username', 'bio')


""" Не работает, надо исправить """


class NewPasswordForm(PasswordChangeForm):
    old_password = forms.CharField(label='Старый пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password1 = forms.CharField(label='Новый пароль', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    new_password2 = forms.CharField(label='Подтверждение пароля',
                                    widget=forms.PasswordInput(attrs={'class': 'form-control'}))

illumail/users/views.py
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import DetailView, CreateView, UpdateView, ListView
from django.contrib.auth.views import LogoutView, LoginView, PasswordChangeView
from .forms import RegisterUser, UpdateProfileForm, NewPasswordForm
from .models import CustomUser


class RegisterNewUser(CreateView):
    form_class = RegisterUser
    template_name = 'register.html'
    extra_context = {'title': 'Регистрация', 'subtitle': 'Регистрация'}

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('show_courses')


class LogoutUser(LogoutView):
    next_page = 'show_courses'


class LoginUser(LoginView):
    template_name = 'login.html'
    next_page = reverse_lazy('show_courses')
    extra_context = {'title': 'Вход'}


class MyProfile(DetailView):
    model = CustomUser
    template_name = 'my_profile.html'
    context_object_name = 'profile'
    extra_context = {'title': 'Мой профиль'}

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cnt_sbs'] = len(CustomUser.objects.get(id=self.request.user.id).subscriptions.all())
        return context


class UpdateProfile(UpdateView):
    form_class = UpdateProfileForm
    template_name = 'update_profile.html'
    extra_context = {'title': 'Изменение профиля'}

    def get_object(self, queryset=None):
        return self.request.user


class NewPassword(PasswordChangeView):
    form_class = NewPasswordForm
    template_name = 'new_password.html'
    success_url = reverse_lazy('show_courses')
    extra_context = {'title': 'Смена пароля'}


class MySubscriptions(ListView):
    template_name = 'subscriptions.html'
    extra_context = {'title': 'Подписки', 'subtitle': 'Вы подписаны на:'}
    context_object_name = 'subscriptions'

    def get_queryset(self):
        return CustomUser.objects.get(id=self.request.user.id).subscriptions.all()


class AnotherUser(DetailView):
    model = CustomUser
    template_name = 'another_user.html'
    extra_context = {'title': 'Пользователь'}

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['another_user'] = CustomUser.objects.get(pk=self.kwargs['pk'])
        context['another_user_courses'] = CustomUser.objects.get(pk=self.kwargs['pk']).user_courses.all()
        if CustomUser.objects.get(pk=self.kwargs['pk']).id < self.request.user.id: #61 16
            context['r_name'] = str(CustomUser.objects.get(pk=self.kwargs['pk']).id) + "_" + str(self.request.user.id) #61_16
        else:
            context['r_name'] = str(self.request.user.id) + "_" + str(CustomUser.objects.get(pk=self.kwargs['pk']).id) # 61_16

        # чтобы появлялась кнопка подписаться/отписаться
        context['is_followed'] = False
        if CustomUser.objects.get(pk=self.kwargs['pk']) in CustomUser.objects.get(id=self.request.user.id).subscriptions.all():
            context['is_followed'] = True
        else:
            context['is_followed'] = False
        return context


def add_subscription(request, pk):
    CustomUser.objects.get(id=request.user.id).subscriptions.add(CustomUser.objects.get(id=pk))
    return HttpResponseRedirect(reverse('my_subscriptions', args=[request.user.id]))


def unsubscribe(request, pk):
    CustomUser.objects.get(id=request.user.id).subscriptions.remove(CustomUser.objects.get(id=pk))
    return HttpResponseRedirect(reverse('my_subscriptions', args=[request.user.id]))


class SearchUsers(ListView):
    model = CustomUser
    template_name = 'search_users.html'
    context_object_name = 'users'
    extra_context = {'title': 'Поиск пользователей', 'subtitle': 'По Вашему запросу найдено:'}

    def get_queryset(self):
        return CustomUser.objects.filter(username__icontains=self.request.GET.get('search', ''))

illumail/users/templates/another_user.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%; margin-bottom: 50px;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Пользователь: {{ another_user.username }}</h2>

    {% else %}
    <h5><i>Авторизуйтесь</i></h5>
    {% endif %}
    {% if another_user.username != request.user.username %}
    {% if is_followed %}
    <a class="teaching_button" href="{% url 'unsubscribe' another_user.pk %}">Отписаться</a>
    {% else %}
    <a class="teaching_button" href="{% url 'add_subscription' another_user.pk %}">Подписаться</a>
    {% endif %}
    {% endif %}

    <div class="card" style="width: 80%; height: 550px; display: flex; flex-direction: column; ">
        <h4>
            {% if another_user.photo %}
            <img src="{{ another_user.photo.url }}" alt=""
                 style="margin-right: 20px; margin-top: -20px; width: 180px; height: 180px; object-fit: cover; border-radius: 50%; display: flex; box-shadow: 1px 3px 12px rgba(0, 0, 0, 0.18); float: left;">
            {% endif %}
        </h4>
        <h3 style="color: white; margin-bottom: 10px;">Имя пользователя: {{ another_user.username }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Имя: {{ another_user.first_name }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Фамилия: {{ another_user.last_name }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Отчество: {{ another_user.patronymic }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Эл.почта: {{ another_user.email }}</h3>
        <h3 style="color: white; margin-bottom: 10px; margin-right: 20px; margin-left: 20px;">О себе: {{ another_user.bio }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Дата регистрации: {{ another_user.time_created }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Дата измененения: {{ another_user.time_updated }}</h3>
    </div>
    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Курсы, в которые вступил {{ another_user.username }}:</h2>
    {% for c in another_user_courses %}

    <div class="card">
        <div class="content">
            <h2>{{ с.title }}</h2>
            <h3>{{ c.title }}</h3><br>
            <p>Дата создания: {{ c.time_created }}<br><br>
                Дата изменения: {{ c.time_updated }}<br>
                Автор: {{ c.author }} ({{ c.author.first_name }})<br>
                {% if c.type_course == '1' %}
                Бесплатно
                {% else %}
                Цена: {{ c.price }} BYN
                {% endif %}
            </p>
            <a href="{{ c.get_absolute_url }}">Подробнее</a>
        </div>
    </div>
    {% endfor %}


</section>
</body>

<script>
    VanillaTilt.init(document.querySelectorAll(".card"), {
		max: 25,
		speed: 400,
		glare: true,
		"max-glare": 1,
	});
	const menuHamburger = document.querySelector(".menu-hamburger")
        const navLinks = document.querySelector(".nav-links")

        menuHamburger.addEventListener('click',()=>{
        navLinks.classList.toggle('mobile-menu')
        })

const button = document.querySelector("button"),
      toast = document.querySelector(".toast")
      closeIcon = document.querySelector(".close"),
      progress = document.querySelector(".progress");
      let timer1, timer2;
      button.addEventListener("click", () => {
        toast.classList.add("active");
        progress.classList.add("active");
        timer1 = setTimeout(() => {
            toast.classList.remove("active");
        }, 5000); //1s = 1000 milliseconds
        timer2 = setTimeout(() => {
          progress.classList.remove("active");
        }, 5300);
      });

      closeIcon.addEventListener("click", () => {
        toast.classList.remove("active");

        setTimeout(() => {
          progress.classList.remove("active");
        }, 300);
        clearTimeout(timer1);
        clearTimeout(timer2);
      });





</script>


</html>

illumail/users/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
</head>
<body>
<form method="post" autocomplete="off">
    {% csrf_token %}
    <section>
        <div class="form-box">
            <div class="form-value">
                <h2>Вход</h2>
                <div class="inputbox">
                    <ion-icon name="person-outline"></ion-icon>
                    <input name="username" class="" required>
                    <label>Имя пользователя</label>
                </div>
                <div class="inputbox">
                    <ion-icon name="lock-closed-outline"></ion-icon>
                    <input name="password" required>
                    <label>Пароль</label>
                </div>

                <button>Войти</button>
                <div class="register">
                    <p>У Вас нет аккаунта?</p>
                    <p><a href="{% url 'register_user' %}">Регистрация</a></p>
                </div>
            </div>
        </div>
    </section>
</form>
<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

</body>
</html>

illumail/users/templates/my_profile.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%; margin-bottom: 50px;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Мой профиль:</h2>

    {% else %}
    <h5><i>Авторизуйтесь</i></h5>
    {% endif %}


    <div class="card" style="width: 80%; height: 550px; display: flex; flex-direction: column; ">
        <h4>
            {% if user.photo %}
            <img src="{{ user.photo.url }}" alt=""
                 style="margin-right: 20px; margin-top: -20px; width: 180px; height: 180px; object-fit: cover; border-radius: 50%; display: flex; box-shadow: 1px 3px 12px rgba(0, 0, 0, 0.18); float: left;">
            {% endif %}
        </h4>
        <h3 style="color: white; margin-bottom: 10px;">Имя пользователя: {{ user.username }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Имя: {{ user.first_name }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Фамилия: {{ user.last_name }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Отчество: {{ user.patronymic }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Эл.почта: {{ user.email }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">О себе: {{ user.bio }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Дата регистрации: {{ user.time_created }}</h3>
        <h3 style="color: white; margin-bottom: 10px;">Дата измененения: {{ user.time_updated }}</h3>
    </div>
    <a class="teaching_button" style="" href="{% url 'update_profile' user.id %}">Изменить профиль</a>
    <a class="teaching_button" href="{% url 'logout_user' %}">Выйти из аккаунта</a>
    <a class="teaching_button" href="{% url 'my_subscriptions' user.id %}">Подписки {{ cnt_sbs }}</a>


</section>
</body>

<script>
    VanillaTilt.init(document.querySelectorAll(".card"), {
		max: 25,
		speed: 400,
		glare: true,
		"max-glare": 1,
	});
	const menuHamburger = document.querySelector(".menu-hamburger")
        const navLinks = document.querySelector(".nav-links")

        menuHamburger.addEventListener('click',()=>{
        navLinks.classList.toggle('mobile-menu')
        })

const button = document.querySelector("button"),
      toast = document.querySelector(".toast")
      closeIcon = document.querySelector(".close"),
      progress = document.querySelector(".progress");
      let timer1, timer2;
      button.addEventListener("click", () => {
        toast.classList.add("active");
        progress.classList.add("active");
        timer1 = setTimeout(() => {
            toast.classList.remove("active");
        }, 5000); //1s = 1000 milliseconds
        timer2 = setTimeout(() => {
          progress.classList.remove("active");
        }, 5300);
      });

      closeIcon.addEventListener("click", () => {
        toast.classList.remove("active");

        setTimeout(() => {
          progress.classList.remove("active");
        }, 300);
        clearTimeout(timer1);
        clearTimeout(timer2);
      });




</script>


</html>

illumail/users/templates/new_password.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 90px;">Смена пароля:</h2>

    <form method="post" style="width: 100%; margin-bottom: 10px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section">
            <div class="form-box" style="height: 400px;">
                <div class="form-value">
                    <div class="inputbox">
                        <input name="old_password" id="id_old_password" class="" required>
                        <label>Старый пароль</label>
                    </div>
                  <div class="inputbox">
                        <input name="new_password1" id="id_new_password1" class="" required>
                        <label>Новый пароль</label>
                    </div>
                  <div class="inputbox">
                        <input name="new_password2" id="id_new_password2" class="" required>
                        <label>Подтверждение пароля</label>
                    </div>
                    <button class="form-button" type="submit">Изменить пароль</button>
                </div>
            </div>
        </section>
    </form>

    {% else %}
    <h5><i>Авторизуйтесь, чтобы изменять данные</i></h5>
    {% endif %}



</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
    VanillaTilt.init(document.querySelectorAll(".card"), {
		max: 25,
		speed: 400,
		glare: true,
		"max-glare": 1,
	});
	const menuHamburger = document.querySelector(".menu-hamburger")
        const navLinks = document.querySelector(".nav-links")

        menuHamburger.addEventListener('click',()=>{
        navLinks.classList.toggle('mobile-menu')
        })

const button = document.querySelector("button"),
      toast = document.querySelector(".toast")
      closeIcon = document.querySelector(".close"),
      progress = document.querySelector(".progress");
      let timer1, timer2;
      button.addEventListener("click", () => {
        toast.classList.add("active");
        progress.classList.add("active");
        timer1 = setTimeout(() => {
            toast.classList.remove("active");
        }, 5000); //1s = 1000 milliseconds
        timer2 = setTimeout(() => {
          progress.classList.remove("active");
        }, 5300);
      });

      closeIcon.addEventListener("click", () => {
        toast.classList.remove("active");

        setTimeout(() => {
          progress.classList.remove("active");
        }, 300);
        clearTimeout(timer1);
        clearTimeout(timer2);
      });


</script>


</html>

illumail/users/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">
</head>
<body>
{% block content %}
<form method="post" autocomplete="off">
    {% csrf_token %}
    <section>
        <div class="form-box">
            <div class="form-value">
                <h2>Регистрация</h2>
                <div class="inputbox">
                    {{ form.first_name }}
                    <label>{{ form.first_name.label }}</label>
                </div>
                <div class="inputbox">
                    {{ form.last_name }}
                    <label>{{ form.last_name.label }}</label>
                </div>
                <div class="inputbox">
                    {{ form.patronymic }}
                    <label>{{ form.patronymic.label }}</label>
                </div>
                <div class="inputbox">
                    {{ form.email }}
                    <label>{{ form.email.label }}</label>
                </div>
                <div class="inputbox">
                    <input name="username" required>
                    <label>{{ form.username.label }}</label>
                </div>
                <div class="inputbox">
                    <input name="password1" required>
                    <label>{{ form.password1.label }}</label>
                </div>
                <div class="inputbox">
                    <input name="password2" required>
                    <label>{{ form.password2.label }}</label>
                </div>
                <button>Регистрация</button>
                <div class="register">
                    <p>У Вас есть аккаунт?</p>
                    <p><a href="{% url 'login_user' %}">Вход</a></p>
                </div>
            </div>
        </div>
    </section>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</form>

{% endblock %}
</body>
</html>

illumail/users/templates/update_profile.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Изменение профиля:</h2>

    <form method="post" style="width: 100%; margin-bottom: 10px; height: 1300px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section">
            <div class="form-box" style="height: 1200px;">
                <div class="form-value">

                    <p style="color: white; text-align: center">Изображение профиля на данный момент:</p>
                    <p><img src="{{ user.photo.url }}" alt="" width="250" height="300" style="margin-left: 35%;"></p>

                    <div class="row" style="color: white;">
                        <label>Новое фото профиля:</label>
                        <input type="file" id="id_photo" name="photo"/>
                    </div>
                    <br>
                    <div class="row" style="color: white;">
                        <span id="output"></span>
                    </div>

                    <div class="inputbox">
                        <input name="first_name" class="" required value="{{ user.first_name }}">
                        <label>Имя</label>
                    </div>
                    <div class="inputbox">
                        <input name="last_name" class="" required value="{{ user.last_name }}">
                        <label>Фамилия</label>
                    </div>
                    <div class="inputbox">
                        <input name="patronymic" class="" required value="{{ user.patronymic }}">
                        <label>Отчество</label>
                    </div>
                    <div class="inputbox">
                        <input name="username" class="" required value="{{ user.username }}">
                        <label>Имя пользователя</label>
                    </div>
                    <div class="inputbox">
                        <input name="email" class="" required value="{{ user.email }}">
                        <label>Эл.почта</label>
                    </div>
                    <div class="inputbox">
                        <input name="bio" class="" required value="{{ user.bio }}">
                        <label>О себе</label>
                    </div>

                    <h3 align="center" style="width: 100%; color: white; margin-top: 30px;">Конфеденциальность:</h3>
                    <a class="teaching_button" style="margin-left: 36%;" href="{% url 'new_password' user.id %}">Изменить пароль</a>
                    <button class="teaching_button" type="submit" style="margin-left: 36%; font-size: 1em;">Сохранить изменения</button>
                </div>
            </div>
        </section>
    </form>

    {% endif %}

</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
function handleFileSelect(evt) {
    var photo = evt.target.files;
    var cp = photo[0];

    if (!cp.type.match('image.*')) {
        alert("Image only please....");
    }
    var reader = new FileReader();

    reader.onload = (function(theFile) {
        return function(e) {

            var span = document.createElement('span');
            span.innerHTML = ['<img class="thumb" width="350" title="', escape(theFile.name), '" src="', e.target.result, '" />'].join('');
            document.getElementById('output').insertBefore(span, null);
        };
    })(cp);

    reader.readAsDataURL(cp);
}
document.getElementById('id_photo').addEventListener('change', handleFileSelect, false);

</script>

{% block javascript %}
<script src="{% static 'courses/js/script.js' %}"></script>
{% endblock %}
</html>