illumail/api/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers


urlpatterns = [
    path('api/courses/', CoursesViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('api/courses/<int:pk>/', CoursesViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),

    path('api/users/<int:pk>/my_profile/', MyProfileAPI.as_view()),
    path('api/users/create/', UserAPICreate.as_view()),

    path('api/auth/', include('rest_framework.urls')),
]

illumail/courses/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', redirectik, name='redirectik'),
    path('courses/', ShowCourses.as_view(), name='show_courses'),
    path('courses/<int:course_id>/posts/', ShowPosts.as_view(), name='show_posts'),
    path('courses/<int:course_id>/posts/<int:post_id>/', show_specific_post, name='show_specific_post'),
    path('courses/create/', CreateCourse.as_view(), name='create_course'),
    path('courses/<int:pk>/update/', UpdateCourse.as_view(), name='update_course'),
    path('courses/<int:pk>/delete/', delete_course, name='delete_course'),
    path('courses/search/', SearchCourse.as_view(), name='search_course'),
    path('courses/teaching/', Teaching.as_view(), name='teaching'),
    path('courses/category/<int:category_id>/', category_courses, name='category_courses'),
    path('learning/', Learning.as_view(), name='learning'),
    path('leave_the_course/<int:pk>/', leave_the_course, name='leave_the_course'),
    path('join_the_course/<int:pk>/', join_the_course, name='join_the_course'),
    path('news/', ShowNews.as_view(), name='show_news'),
    path('courses/<int:course_id>/posts/create/', CreatePost.as_view(), name='create_post'),
    path('courses/<int:pk>/posts/<int:post_id>/delete/', delete_post, name='delete_post'),
    path('courses/<int:pk>/posts/create_test/', CreateTest.as_view(), name='create_test'),
    path('courses/<int:pk>/posts/test/<int:test_id>/', ShowSpecificTest.as_view(), name='show_specific_test'),
    path('courses/sort/', SortCourses.as_view(), name='sort_courses'),
    path('courses/filter/', FilterCourses.as_view(), name='filter_courses'),
    path('courses/new_test/', create_test, name='new_test'),

    path('course/<int:course_id>/test/<int:pk>/', GoodTest.as_view(), name='good_test'),
    # path('course/<int:course_id>/test/<int:pk>/questions/<int:question_id>/save/', save_user_answer, name='save_user_answer'),
    path('course/<int:pk>/test/questions/<int:question_id>/save/', save_user_answer, name='save_user_answer'),
]

illumail/illumail/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat/", include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('', include('users.urls')),
    path('', include('courses.urls')),
    path('', include('study_groups.urls')),
    path('', include('payments.urls')),
    path('', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

illumail/courses/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse
from users.models import CustomUser


class Courses(models.Model):
    CHOICES = [
        ('1', 'Публичный'),
        ('2', 'Платный'),
    ]


    title = models.CharField(max_length=300, verbose_name='Название')
    course_photo = models.ImageField(upload_to='courses_headers/%Y/%m/%d', default='dflt_crs_hdrs.jpg', verbose_name='Изображение курса')
    about_the_course = models.TextField(verbose_name='О курсе')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    author = models.ForeignKey(CustomUser, on_delete=models.PROTECT, verbose_name='Автор курса', related_name='course')
    category = models.ForeignKey('Category', on_delete=models.PROTECT, verbose_name='Категория')
    type_course = models.CharField(max_length=200, choices=CHOICES, default='1', verbose_name='Тип курса')
    price = models.IntegerField(verbose_name='Цена', blank=True, null=True)



    def get_absolute_url(self):
        return reverse('show_posts', kwargs={'course_id': self.id})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'
        ordering = ['-time_created', ]


class Category(models.Model):
    title = models.CharField(max_length=300, verbose_name='Название')

    def get_absolute_url(self):
        return reverse('category_courses', kwargs={'category_id': self.id})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Posts(models.Model):
    CHOICES = [
        ('1', 'Лекция'),
        ('2', 'Практика'),
    ]
    title = models.CharField(max_length=300, verbose_name='Название')
    photo = models.ImageField(upload_to='posts_images/%Y/%m/%d', blank=True, verbose_name='Изображение')
    file = models.FileField(upload_to='files/%Y/%m/%d', blank=True, verbose_name='Файл')
    post_text = models.TextField(verbose_name='Текст поста', blank=True)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name='Курс')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменеия')
    post_type = models.CharField(max_length=200, choices=CHOICES, verbose_name='Тип поста')

    def get_absolute_url(self):
        return reverse('show_specific_post', kwargs={'course_id': self.course.id, 'post_id': self.id})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Материал курса'
        verbose_name_plural = 'Материалы курса'
        ordering = ['-time_created', ]


class CompletedTaskModel(models.Model):
    file = models.FileField(upload_to='compl_tasks/%Y/%m/%d', blank=True, verbose_name='Файл')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь')
    post = models.ForeignKey(Posts, on_delete=models.CASCADE, verbose_name='Пост')
    time_load = models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')

    def __str__(self):
        return f"{self.file}"

    class Meta:
        verbose_name = 'Выполненное задание'
        verbose_name_plural = 'Выполненные задания'
        ordering = ['-time_load', ]


class Comments(models.Model):
    comment_text = models.CharField(max_length=300, verbose_name='Текст комментария')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Автор комментария')
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name='Курс с комментарием')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')

    def __str__(self):
        return f"{self.comment_text}"

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-time_created']


class Quiz(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name='Курс')
    title = models.CharField(max_length=300, verbose_name='Название теста')
    question = models.CharField(max_length=300, verbose_name='Вопрос')
    true_answer = models.CharField(max_length=300, verbose_name='Правильный ответ')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'Тест с вписыванием ответа'
        verbose_name_plural = 'Тесты с вписыванием ответа'
        ordering = ['-time_created', ]


class Answer(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, verbose_name='Тест')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь')
    user_answer = models.CharField(max_length=300, verbose_name='Ответ пользователя')

    def __str__(self):
        return f"{self.quiz}"

    class Meta:
        verbose_name = 'Ответ на тест в вписыванем'
        verbose_name_plural = 'Ответы на тест в вписыванем'


class Testing(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()


class Question(models.Model):
    test = models.ForeignKey(Testing, on_delete=models.CASCADE)
    text = models.TextField()


class Reply(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField()
    is_correct = models.BooleanField(default=False)


class GoodTestModel(models.Model):
    title = models.CharField(max_length=300, verbose_name='Название теста')
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name='Курс')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Тест'
        verbose_name_plural = 'Тесты'


class QuestionModel(models.Model):
    test = models.ForeignKey(GoodTestModel, on_delete=models.CASCADE, verbose_name='Название теста')
    question = models.CharField(max_length=500, verbose_name='Вопрос')
    true_answer = models.CharField(max_length=500, verbose_name='Правильный ответ')

    def __str__(self):
        return self.question

    class Meta:
        verbose_name = 'Вопрос'
        verbose_name_plural = 'Вопросы'


class AnswerModel(models.Model):
    question = models.ForeignKey(QuestionModel, on_delete=models.CASCADE, verbose_name='Вопрос')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь')
    user_answer = models.CharField(max_length=300, verbose_name='Ответ пользователя')

    def __str__(self):
        return f"{self.question}"

    class Meta:
        verbose_name = 'Ответ на тест'
        verbose_name_plural = 'Ответы на тест'


class Progress(models.Model):
    course = models.ForeignKey(Courses, on_delete=models.CASCADE, verbose_name='Курс')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь')
    progress = models.IntegerField(validators=[MaxValueValidator(limit_value=100), ], default=0, verbose_name='Прогресс')

    def __str__(self):
        return f"{self.progress}"

    class Meta:
        verbose_name = 'Прогресс'
        verbose_name_plural = 'Прогресс'

illumail/courses/forms.py
from django import forms
from .models import *


class ComplitedTaskForm(forms.ModelForm):
    # file = forms.FileField(label='Файл', widget=forms.ClearableFileInput(attrs={'multiple': True}))
    file = forms.FileField(label='Файл')

    class Meta:
        model = CompletedTaskModel
        fields = ['file', ]


class CreateOrUpdateCourseForm(forms.ModelForm):
    about_the_course = forms.CharField(widget=forms.Textarea(attrs={'cols': 85, 'rows': 15}))

    class Meta:
        model = Courses
        fields = ['title', 'course_photo', 'about_the_course', 'category', 'price']


class CreateOrUpdatePostForm(forms.ModelForm):
    # post_type = forms.ChoiceField(choices=Posts.CHOICES, widget=forms.RadioSelect(), required=True, label='Тип задания')

    class Meta:
        model = Posts
        fields = ['title', 'photo', 'file', 'post_text']


class CommentForm(forms.ModelForm):
    comment_text = forms.CharField(label='Текст комментария', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = Comments
        fields = ['comment_text', ]


class CreateTestForm(forms.ModelForm):
    title = forms.CharField(label='Название теста', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    question = forms.CharField(label='Вопрос', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control'}))
    true_answer = forms.CharField(label='Правильный ответ', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = Quiz
        fields = ['title', 'question', 'true_answer']


class AnswerForm(forms.ModelForm):
    user_answer = forms.CharField(label='Ответ на вопрос', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = Answer
        fields = ['user_answer', ]


class TestingForm(forms.ModelForm):
    class Meta:
        model = Testing
        fields = ['name', 'description']


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text']


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['text', 'is_correct']


"""Новое"""


class GoodAnswerForm(forms.ModelForm):
    user_answer = forms.CharField(label='Ответ на вопрос', required=True, widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = AnswerModel
        fields = ['user_answer', ]

illumail/courses/templates/course_test.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% for q in questions %}
    <div class="card">
        <div class="card-body">
        <h3>{{ q.question }}</h3>
            </div>
    </div>
    <br>

    <form method="post" autocomplete="off" action="{% url 'save_user_answer' q.test.course.pk q.pk %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Сдать тест</button>
        <br>
        <br>
    {% endfor %}

    </form>
</div>
{% endblock %}

illumail/courses/templates/create_course.html
 {% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Создание курса:</h2>

    <form method="post" style="width: 100%; margin-bottom: 10px; height: 700px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section">
            <div class="form-box" style="height: 600px;">
                <div class="form-value">
                    <div class="inputbox">
                        <input name="title" class="" required>
                        <label>Название курса</label>
                    </div>
                    <div class="inputbox">
                        <input name="about_the_course" class="" required>
                        <label>Описание курса</label>
                    </div>


                    <p style="color: white;">Категория:</p>

                    <div class="dropdown">
                        <div class="select">
                            <span class="selected" id="id_category">Не выбрано</span>
                            <div class="caret"></div>
                        </div>
                        <ul class="menu">
<!--                            {% for f in form.category %}-->
<!--                            <li>{{ f }}</li>-->
<!--                            {% endfor %}-->
                            {{ form.category }}

                        </ul>
                    </div>

                    <div class="row" style="color: white;">
                        <label>Фото курса:</label>
                        <input  style="" type="file" id="id_course_photo" name="course_photo"/>
                    </div>
                    <br>
                    <div class="row" style="color: white;">
                        <span id="output"></span>
                    </div>

                    <button class="form-button" type="submit">Добавить</button>
                </div>
            </div>
        </section>
    </form>

    {% endif %}

</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
function handleFileSelect(evt) {
    var course_photo = evt.target.files;
    var cp = course_photo[0];

    if (!cp.type.match('image.*')) {
        alert("Image only please....");
    }
    var reader = new FileReader();

    reader.onload = (function(theFile) {
        return function(e) {

            var span = document.createElement('span');
            span.innerHTML = ['<img class="thumb" width="350" title="', escape(theFile.name), '" src="', e.target.result, '" />'].join('');
            document.getElementById('output').insertBefore(span, null);
        };
    })(cp);

    reader.readAsDataURL(cp);
}
document.getElementById('id_course_photo').addEventListener('change', handleFileSelect, false);


    const dropdowns = document.querySelectorAll('.dropdown');
    dropdowns.forEach(dropdown => {
        const select = dropdown.querySelector('.select');
        const caret = dropdown.querySelector('.caret');
        const menu = dropdown.querySelector('.menu');
        const options = dropdown.querySelectorAll('.menu li');
        const selected = dropdown.querySelector('.selected');

    select.addEventListener('click', () => {
        select.classList.toggle('select-clicked');
        caret.classList.toggle('caret-rotate');
        menu.classList.toggle('menu-open');
    });

    options.forEach(option => {
        option.addEventListener('click', () => {
            selected.innerText = option.innerText;
            select.classList.remove('select-clicked');
            caret.classList.remove('caret-rotate');
            menu.classList.remove('menu-open');
            option.forEach(option => {
                option.classList.remove('active');
            });
            option.classList.add('active');
        });
    });
});
</script>

{% block javascript %}
<script src="{% static 'courses/js/script.js' %}"></script>
{% endblock %}
</html>

illumail/courses/templates/create_quiz.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Добавить тест:</h2>

    <form method="post" style="width: 100%; margin-bottom: 10px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section" style="margin-bottom: 200px;">
            <div class="form-box" style="height: 400px;">
                <div class="form-value">
                    <div class="inputbox">
                        <input name="title" id="id_title" class="" required>
                        <label>Название теста</label>
                    </div>
                  <div class="inputbox">
                        <input name="question" id="id_question" class="" required>
                        <label>Вопрос:</label>
                    </div>
                  <div class="inputbox">
                        <input name="true_answer" id="id_true_answer" class="" required>
                        <label>Правильный ответ</label>
                    </div>
                    <button class="form-button" type="submit">Создать тест</button>
                </div>
            </div>
        </section>
    </form>

    {% else %}
    <h5><i>Авторизуйтесь, чтобы создавать тесты</i></h5>
    {% endif %}



</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
    VanillaTilt.init(document.querySelectorAll(".card"), {
		max: 25,
		speed: 400,
		glare: true,
		"max-glare": 1,
	});
	const menuHamburger = document.querySelector(".menu-hamburger")
        const navLinks = document.querySelector(".nav-links")

        menuHamburger.addEventListener('click',()=>{
        navLinks.classList.toggle('mobile-menu')
        })

const button = document.querySelector("button"),
      toast = document.querySelector(".toast")
      closeIcon = document.querySelector(".close"),
      progress = document.querySelector(".progress");
      let timer1, timer2;
      button.addEventListener("click", () => {
        toast.classList.add("active");
        progress.classList.add("active");
        timer1 = setTimeout(() => {
            toast.classList.remove("active");
        }, 5000); //1s = 1000 milliseconds
        timer2 = setTimeout(() => {
          progress.classList.remove("active");
        }, 5300);
      });

      closeIcon.addEventListener("click", () => {
        toast.classList.remove("active");




</script>


</html>

illumail/courses/templates/create_task.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Добавить лекцию:</h2>

    <form method="post" style="width: 100%; margin-bottom: 10px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section" style="margin-bottom: 200px;">
            <div class="form-box" style="height: 500px;">
                <div class="form-value">
                    <div class="inputbox">
                        <input name="title" id="id_title" class="" required>
                        <label>Название:</label>
                    </div>
                  <div class="inputbox">
                        <input name="post_text" id="id_post_text" class="" required>
                        <label>Текст лекции:</label>
                    </div>
                   <div class="row" style="color: white;">
                        <label>Изображение:</label>
                        <input type="file" id="id_course_photo" name="course_photo"/>
                    </div>
                    <br>
                    <div class="row" style="color: white;">
                        <span id="output"></span>
                    </div>

                  <div class="" style="color: white;">
                        <label>Файл:</label>
                        <input type="file" id="id_file" name="file"/>
                    </div>
                    <button class="form-button" type="submit">Создать лекцию</button>
                </div>
            </div>
        </section>
    </form>

    {% else %}
    <h5><i>Авторизуйтесь, чтобы создавать тесты</i></h5>
    {% endif %}



</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
    VanillaTilt.init(document.querySelectorAll(".card"), {
		max: 25,
		speed: 400,
		glare: true,
		"max-glare": 1,
	});
	const menuHamburger = document.querySelector(".menu-hamburger")
        const navLinks = document.querySelector(".nav-links")

        menuHamburger.addEventListener('click',()=>{
        navLinks.classList.toggle('mobile-menu')
        })

const button = document.querySelector("button"),
      toast = document.querySelector(".toast")
      closeIcon = document.querySelector(".close"),
      progress = document.querySelector(".progress");
      let timer1, timer2;
      button.addEventListener("click", () => {
        toast.classList.add("active");
        progress.classList.add("active");
        timer1 = setTimeout(() => {
            toast.classList.remove("active");
        }, 5000); //1s = 1000 milliseconds
        timer2 = setTimeout(() => {
          progress.classList.remove("active");
        }, 5300);
      });

      closeIcon.addEventListener("click", () => {
        toast.classList.remove("active");




</script>
<script>
  function handleFileSelect(evt) {
    var course_photo = evt.target.files;
    var cp = course_photo[0];

    if (!cp.type.match('image.*')) {
        alert("Image only please....");
    }
    var reader = new FileReader();

    reader.onload = (function(theFile) {
        return function(e) {

            var span = document.createElement('span');
            span.innerHTML = ['<img class="thumb" width="350" title="', escape(theFile.name), '" src="', e.target.result, '" />'].join('');
            document.getElementById('output').insertBefore(span, null);
        };
    })(cp);

    reader.readAsDataURL(cp);
}
document.getElementById('id_course_photo').addEventListener('change', handleFileSelect, false);
</script>

</html>

illumail/courses/templates/create_test.html
{% extends 'base.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ test_form.as_p }}
    <input type="number" name="question_count" value="5">
    <input type="number" name="answer_count" value="4">
    {% for qform in question_forms %}
        {{ qform.as_p }}
        {% for aform in answer_forms %}
            {% if aform.prefix == qform.prefix %}
                {{ aform.as_p }}
            {% endif %}
        {% endfor %}
    {% endfor %}
    <button type="submit">Create Test</button>
</form>

{% endblock %}

illumail/courses/templates/specific_test.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px; padding-top: 200px;">Название: {{ test.title }}</h2>
  <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Вопрос: {{ test.question }}</h2>

    <form method="post" style="width: 100%; margin-bottom: 10px; padding-bottom: 200px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section">
            <div class="form-box">
                <div class="form-value">
                    <div class="inputbox">
                        <input name="user_answer" id="id_user_answer" class="" required>
                        <label>Введите текст</label>
                    </div>
                    <button class="form-button" type="submit">Ответить</button>
                </div>
            </div>
        </section>
    </form>
  {% endif %}

</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
    VanillaTilt.init(document.querySelectorAll(".card"), {
		max: 25,
		speed: 400,
		glare: true,
		"max-glare": 1,
	});
	const menuHamburger = document.querySelector(".menu-hamburger")
        const navLinks = document.querySelector(".nav-links")

        menuHamburger.addEventListener('click',()=>{
        navLinks.classList.toggle('mobile-menu')
        })

const button = document.querySelector("button"),
      toast = document.querySelector(".toast")
      closeIcon = document.querySelector(".close"),
      progress = document.querySelector(".progress");
      let timer1, timer2;
      button.addEventListener("click", () => {
        toast.classList.add("active");
        progress.classList.add("active");
        timer1 = setTimeout(() => {
            toast.classList.remove("active");
        }, 5000); //1s = 1000 milliseconds
        timer2 = setTimeout(() => {
          progress.classList.remove("active");
        }, 5300);
      });

      closeIcon.addEventListener("click", () => {
        toast.classList.remove("active");

        setTimeout(() => {
          progress.classList.remove("active");
        }, 300);
        clearTimeout(timer1);
        clearTimeout(timer2);
      });


</script>


</html>