illumail/api/urls.py
from django.urls import path, include
from .views import *
from rest_framework import routers


urlpatterns = [
    path('api/courses/', CoursesViewSet.as_view({'get': 'list', 'post': 'create'})),
    path('api/courses/<int:pk>/', CoursesViewSet.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'})),

    path('api/users/<int:pk>/my_profile/', MyProfileAPI.as_view()),
    path('api/users/create/', UserAPICreate.as_view()),

    path('api/auth/', include('rest_framework.urls')),
]

illumail/illumail/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("chat/", include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('', include('users.urls')),
    path('', include('courses.urls')),
    path('', include('study_groups.urls')),
    path('', include('payments.urls')),
    path('', include('forum.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

illumail/study_groups/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('study_group/<int:pk>/posts/', ShowPostsGroups.as_view(), name='show_posts_group'),
    path('study_group/<int:pk>/posts/<int:post_id>/', show_specific_task, name='show_specific_task'),
    path('study_group/<int:pk>/tasks/<int:post_id>/delete/', delete_task, name='delete_task'),
    path('study_group/create/', CreateGroup.as_view(), name='create_group'),
    path('study_group/<int:pk>/update/', UpdateGroup.as_view(), name='update_group'),
    path('study_group/<int:pk>/delete/', delete_group, name='delete_group'),
    path('study_group/<int:study_group_id>/posts/create/', CreateTask.as_view(), name='create_task'),
    path('study_group/<int:pk>/students/', ShowStudents.as_view(), name='show_students'),
    path('study_group/<int:pk>/posts/<int:post_id>/grades/', show_valuations, name='show_valuations'),
    path('study_group/<int:pk>/posts/<int:post_id>/grades/<int:work_id>/', save_update_valuations, name='save_update_valuations'),
    path('study_group/<int:pk>/posts/leave_the_group/', leave_the_group, name='leave_the_group'),
    path('study_group/join_the_group', join_the_group, name='join_the_group'),
    path('study_group/<int:group_id>/my_valuations/', MyValuations.as_view(), name='my_valuations'),
]

illumail/study_groups/models.py
from django.core.validators import MaxValueValidator
from django.db import models
from django.urls import reverse
from users.models import CustomUser
from .rand_code import generate_alphanum_crypt_string


class StudyGroup(models.Model):
    title = models.CharField(max_length=300, verbose_name='Название')
    group_photo = models.ImageField(upload_to='groups_headers/%Y/%m/%d', default='dflt_crs_hdrs.jpg',
                                    verbose_name='Изображение группы')
    about_the_group = models.TextField(verbose_name='О группе')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    author = models.ForeignKey(CustomUser, on_delete=models.PROTECT, verbose_name='Автор группы',
                               related_name='study_groups')
    group_code = models.CharField(max_length=10, default=generate_alphanum_crypt_string, verbose_name='Код группы', unique=True)

    def get_absolute_url(self):
        return reverse('show_posts_group', kwargs={'pk': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Учебная группа'
        verbose_name_plural = 'Учебные группы'
        ordering = ['-time_created', ]


class PostsInStudyGroup(models.Model):
    CHOICES = [
        ('1', 'Лекция'),
        ('2', 'Практика'),
    ]
    title = models.CharField(max_length=300, verbose_name='Название')
    photo = models.ImageField(upload_to='posts_images/%Y/%m/%d', blank=True, verbose_name='Изображение')
    file = models.FileField(upload_to='files/%Y/%m/%d', blank=True, verbose_name='Файл')
    post_text = models.TextField(verbose_name='Текст поста', blank=True)
    study_group = models.ForeignKey(StudyGroup, on_delete=models.CASCADE, verbose_name='Учебная группа')
    time_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_updated = models.DateTimeField(auto_now=True, verbose_name='Дата изменеия')
    post_type = models.CharField(max_length=200, choices=CHOICES, verbose_name='Тип поста')

    def get_absolute_url(self):
        return reverse('show_specific_task', kwargs={'pk': self.study_group.id, 'post_id': self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Материал группы'
        verbose_name_plural = 'Метериалы группы'
        ordering = ['-time_created', ]


class CompletedTaskInStudyGroup(models.Model):
    file = models.FileField(upload_to='compl_tasks/%Y/%m/%d', blank=True, verbose_name='Файл')
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name='Пользователь')
    post = models.ForeignKey(PostsInStudyGroup, on_delete=models.CASCADE, verbose_name='Задание')
    time_load = models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')
    grade = models.IntegerField(validators=[MaxValueValidator(limit_value=10), ], verbose_name='Оценка', default="0")

    def __str__(self):
        return f"{self.file}"

    class Meta:
        verbose_name = 'Выполненное задание'
        verbose_name_plural = 'Выполненные задания'
        ordering = ['-time_load', ]


















# Удалить модель
class Valuation(models.Model):
    post_task = models.ForeignKey(PostsInStudyGroup, on_delete=models.PROTECT, verbose_name='Задание')
    compl_task = models.ForeignKey(CompletedTaskInStudyGroup, on_delete=models.PROTECT,
                                   verbose_name='Выполненное задание', related_name='valuations')
    user = models.ForeignKey(CustomUser, on_delete=models.PROTECT, verbose_name='Учащийся')
    valuation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата оценивания')
    grade = models.IntegerField(validators=[MaxValueValidator(limit_value=10), ], verbose_name='Оценка')

    def __str__(self):
        return f"{self.user}-{self.post_task}"

    class Meta:
        verbose_name = 'Оценка'
        verbose_name_plural = 'Оценки'

illumail/study_groups/forms.py
from django import forms
from django.forms import inlineformset_factory, formset_factory

from .models import CompletedTaskInStudyGroup, StudyGroup, PostsInStudyGroup


class ComplitedTaskGroupForm(forms.ModelForm):
    #file = forms.FileField(label='Файл', widget=forms.ClearableFileInput(attrs={'multiple': True}))
    file = forms.FileField(label='Файл')

    class Meta:
        model = CompletedTaskInStudyGroup
        fields = ['file', ]


class CreateOrUpdateGroupForm(forms.ModelForm):
    about_the_group = forms.CharField(widget=forms.Textarea(attrs={'cols': 85, 'rows': 15}))

    class Meta:
        model = StudyGroup
        fields = ['title', 'group_photo', 'about_the_group']


class CreateOrUpdatePostForm(forms.ModelForm):
    post_type = forms.ChoiceField(choices=PostsInStudyGroup.CHOICES, widget=forms.RadioSelect(), required=True, label='Тип задания')

    class Meta:
        model = PostsInStudyGroup
        fields = ['title', 'photo', 'file', 'post_text', 'post_type']


class UpdateValuations(forms.ModelForm):
    class Meta:
        model = CompletedTaskInStudyGroup
        fields = ['grade', ]

illumail/study_groups/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView
from users.models import CustomUser
from .models import PostsInStudyGroup, StudyGroup, Valuation
from .forms import *
from django.contrib import messages


class ShowPostsGroups(ListView):
    model = PostsInStudyGroup
    template_name = 'study_group.html'
    extra_context = {'title': 'Учебная группа', 'subtitle': 'Группа'}

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts'] = PostsInStudyGroup.objects.filter(study_group_id=self.kwargs['pk'])
        # для вывод инфы о группе и для вывода кнопок управления
        context['study_group'] = StudyGroup.objects.get(id=self.kwargs['pk'])

        context['is_followed'] = False
        if StudyGroup.objects.get(id=self.kwargs['pk']) in CustomUser.objects.get(id=self.request.user.id).user_groups.all():
            context['is_followed'] = True
        else:
            context['is_followed'] = False
        return context


def show_specific_task(request, pk, post_id):
    posts_in_group = PostsInStudyGroup.objects.filter(study_group_id=pk)
    post = PostsInStudyGroup.objects.get(id=post_id)

    if request.method == "POST":
        form = ComplitedTaskGroupForm(request.POST, request.FILES)
        files = request.FILES.getlist('file')
        if form.is_valid():
            for f in files:
                file_instance = CompletedTaskInStudyGroup(file=f)
                file_instance.user = request.user
                file_instance.post = post
                file_instance.save()
            return HttpResponseRedirect(reverse('show_posts_group', args=[post.study_group.pk]))
    else:
        form = ComplitedTaskGroupForm()

    context = {
        'posts_in_group': posts_in_group,
        'post': post,
        'form': form,
        'title': post.title,
    }
    return render(request, 'specific_task.html', context)


def delete_task(request, pk, post_id):
    study_group = StudyGroup.objects.get(id=pk)
    task = PostsInStudyGroup.objects.get(id=post_id)
    task.delete()
    return HttpResponseRedirect(reverse('show_posts_group', args=[study_group.id]))


class CreateGroup(CreateView):
    form_class = CreateOrUpdateGroupForm
    template_name = 'create_group.html'
    success_url = reverse_lazy('teaching')
    extra_context = {'title': 'Создание группы'}

    def form_valid(self, form):
        fs = form.save(commit=False)
        fs.author = self.request.user
        fs.save()
        return redirect('teaching')


class UpdateGroup(UpdateView):
    form_class = CreateOrUpdateGroupForm
    template_name = 'update_group.html'
    extra_context = {'title': 'Изменить группу'}
    context_object_name = 'group'
    queryset = StudyGroup.objects.all()

    def form_valid(self, form):
        fs = form.save(commit=False)
        fs.author = self.request.user
        fs.save()
        return redirect('teaching')


def delete_group(request, pk):
    group = StudyGroup.objects.get(id=pk)
    group.delete()
    return HttpResponseRedirect(reverse('teaching'))


def leave_the_group(request, pk):
    StudyGroup.objects.get(id=pk).customuser_set.remove(request.user)
    return HttpResponseRedirect(reverse('learning'))


class CreateTask(CreateView):
    form_class = CreateOrUpdatePostForm
    template_name = 'create_new_task.html'
    extra_context = {'title': 'Создание задания'}

    def form_valid(self, form):
        fs = form.save(commit=False)
        fs.study_group_id = self.kwargs['study_group_id']
        fs.save()
        return redirect('show_posts_group', pk=fs.study_group_id)


class ShowStudents(ListView):
    model = StudyGroup
    template_name = 'students.html'
    extra_context = {'title': 'Учащиеся', 'subtitle': 'Учащиеся данной группы'}

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_users'] = CustomUser.objects.all()
        context['students'] = StudyGroup.objects.get(id=self.kwargs['pk']).customuser_set.all()
        return context


class ShowValuations(CreateView):
    form_class = UpdateValuations
    template_name = 'compl_works.html'
    extra_context = {'title': 'Оценки', 'subtitle': 'Работы и оценки учащихся'}

    def form_valid(self, form):
        fs = form.save(commit=False)
        fs.post_id = self.kwargs['post_id']
        fs.user_id = self.request.user.id
        fs.save()
        return HttpResponseRedirect(reverse('show_valuations', args=[self.kwargs['pk'], self.kwargs['post_id']]))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['compl_works'] = CompletedTaskInStudyGroup.objects.filter(post_id=PostsInStudyGroup.objects.get(pk=self.kwargs['post_id']))
        return context


class MyValuations(ListView):
    model = Valuation
    template_name = 'my_valuations.html'
    extra_context = {'title': 'Мои оценки', 'subtitle': 'Мои оценки'}

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['my_valuations'] = CompletedTaskInStudyGroup.objects.filter(post_id__in=PostsInStudyGroup.objects.filter(study_group_id=self.kwargs['group_id']), user=self.request.user.id)
        try:
            context['avg_grade'] = sum([i.grade for i in context['my_valuations']]) / len(context['my_valuations'])
        except ZeroDivisionError:
            context['avg_grade'] = 'Отсутствует. У Вас нет оценок.'
        return context


def show_valuations(request, pk, post_id):
    study_group = StudyGroup.objects.get(pk=pk)
    compl_works = CompletedTaskInStudyGroup.objects.filter(post_id=PostsInStudyGroup.objects.get(pk=post_id))
    form = UpdateValuations()
    if request.method == "POST":
        form = UpdateValuations(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('show_valuations', args=[study_group.id, post_id]))

    context = {
        'study_group': study_group, 'compl_works': compl_works, 'form': form, 'title': 'Работы и оценки'
    }
    return render(request, 'compl_works.html', context)


def save_update_valuations(request, pk, post_id, work_id):
    study_group = StudyGroup.objects.get(pk=pk)
    compl_works = CompletedTaskInStudyGroup.objects.filter(post_id=PostsInStudyGroup.objects.get(pk=post_id))
    work = CompletedTaskInStudyGroup.objects.get(pk=work_id)
    if request.method == "POST":
        form = UpdateValuations(request.POST, request.FILES, instance=work)
        if form.is_valid():
            fs = form.save(commit=False)
            fs.post_id = PostsInStudyGroup.objects.get(pk=post_id).id #?
            fs.grade = form.cleaned_data['grade']
            fs.save()
    return HttpResponseRedirect(reverse('show_valuations', args=[study_group.id, post_id]))


def join_the_group(request):
    message_ok = False
    try:
        code = StudyGroup.objects.get(group_code=request.GET.get('code', ))
        StudyGroup.objects.get(id=code.pk).customuser_set.add(request.user)
        message_ok = True
    except Exception:
        message_ok = False
        return HttpResponseRedirect(reverse('learning'))
    return HttpResponseRedirect(reverse('learning'))

illumail/study_groups/templates/compl_works.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Выполненные работы:</h2>

    {% for cw in compl_works %}
    <div class="card" style="width: 85%; height: 250px; display: flex; flex-direction: column; ">
        <h4>
            {% if cw.user.photo %}
            <img src="{{ cw.user.photo.url }}" alt=""
                 style="margin-right: 20px; margin-top: -20px; width: 70px; height: 70px; object-fit: cover; border-radius: 50%; display: flex; box-shadow: 1px 3px 12px rgba(0, 0, 0, 0.18); float: left;">
            {% endif %}
            <a style="text-decoration: none; color: white;" class="btn btn-outline-secondary" href="{% url 'another_user' cw.user.pk %}">{{ cw.user.username }}</a>
        </h4>
        <h3 style="color: white;">Учащийся: {{ cw.user.last_name }} {{ cw.user.first_name }} {{ cw.user.patronymic }} ({{ cw.user }}</h3>
        <h3 style="color: white;">Задание: {{ cw.post }}</h3>
        <h3 style="color: white;">Выполненное задание:
            <object data="data/test.pdf" type="application/docx" width="300" height="200">
                        <a href="{{ cw.file.url }}" style="text-decoration: none; color: purple;">{{ cw.file }}</a>
                    </object>
        </h3>
        <h3 style="color: white;">Оценка: {{ cw.grade }}</h3>
        <h3 style="color: white;">Дата сдачи работы: {{ cw.time_load }}</h3>
    </div>


    <form method="post" enctype="multipart/form-data" action="{% url 'save_update_valuations' cw.post.study_group.id cw.post.id cw.id %}" style="width: 100%; margin-bottom: 30px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section">
            <div class="form-box">
                <div class="form-value">
                    <div class="inputbox">
                        <input type="text" name="grade" id="" value="{{ cw.grade }}">
                        <label>Оценка</label>
                    </div>
                    <button class="form-button" type="submit">Поставить оценку</button>
                </div>
            </div>
        </section>
    </form>
    {% endfor %}
{% endif %}
</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
    VanillaTilt.init(document.querySelectorAll(".card"), {
		max: 25,
		speed: 400,
		glare: true,
		"max-glare": 1,
	});
	const menuHamburger = document.querySelector(".menu-hamburger")
        const navLinks = document.querySelector(".nav-links")

        menuHamburger.addEventListener('click',()=>{
        navLinks.classList.toggle('mobile-menu')
        })

const button = document.querySelector("button"),
      toast = document.querySelector(".toast")
      closeIcon = document.querySelector(".close"),
      progress = document.querySelector(".progress");
      let timer1, timer2;
      button.addEventListener("click", () => {
        toast.classList.add("active");
        progress.classList.add("active");
        timer1 = setTimeout(() => {
            toast.classList.remove("active");
        }, 5000); //1s = 1000 milliseconds
        timer2 = setTimeout(() => {
          progress.classList.remove("active");
        }, 5300);
      });

      closeIcon.addEventListener("click", () => {
        toast.classList.remove("active");

        setTimeout(() => {
          progress.classList.remove("active");
        }, 300);
        clearTimeout(timer1);
        clearTimeout(timer2);
      });


</script>


</html>

illumail/study_groups/templates/create_group.html
 {% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Создание учебной группы:</h2>

    <form method="post" style="width: 100%; margin-bottom: 10px; height: 600px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section">
            <div class="form-box" style="height: 500px;">
                <div class="form-value">
                    <div class="inputbox">
                        <input name="title" class="" required>
                        <label>Название группы</label>
                    </div>
                    <div class="inputbox">
                        <input name="about_the_group" class="" required>
                        <label>Описание группы</label>
                    </div>



                    <div class="row" style="color: white;">
                        <label>Фото группы:</label>
                        <input type="file" id="id_group_photo" name="group_photo"/>
                    </div>
                    <br>
                    <div class="row" style="color: white;">
                        <span id="output"></span>
                    </div>

                    <button class="form-button" type="submit">Добавить</button>
                </div>
            </div>
        </section>
    </form>

    {% endif %}

</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
function handleFileSelect(evt) {
    var group_photo = evt.target.files;
    var cp = group_photo[0];

    if (!cp.type.match('image.*')) {
        alert("Image only please....");
    }
    var reader = new FileReader();

    reader.onload = (function(theFile) {
        return function(e) {

            var span = document.createElement('span');
            span.innerHTML = ['<img class="thumb" width="350" title="', escape(theFile.name), '" src="', e.target.result, '" />'].join('');
            document.getElementById('output').insertBefore(span, null);
        };
    })(cp);

    reader.readAsDataURL(cp);
}
document.getElementById('id_group_photo').addEventListener('change', handleFileSelect, false);
</script>

{% block javascript %}
<script src="{% static 'courses/js/script.js' %}"></script>
{% endblock %}
</html>

illumail/study_groups/templates/create_new_task.html
{% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Создание задания:</h2>

    <form method="post" style="width: 100%; margin-bottom: 10px; height: 600px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section">
            <div class="form-box" style="height: 500px;">
                <div class="form-value">
                    <div class="inputbox">
                        <input name="title" class="" required>
                        <label>Название:</label>
                    </div>
                    <div class="inputbox">
                        <input name="post_text" class="" required>
                        <label>Описание задания</label>
                    </div>


                    <div class="row" style="color: white;">
                        <label>Изображение:</label>
                        <input type="file" accept="image/*" id="id_photo" name="photo"/>
                    </div>

                    <div class="row" style="color: white;">
                        <span id="output"></span>
                    </div>

                    <div class="" style="color: white;">
                        <label>Файл:</label>
                        <input type="file" id="id_file" name="file"/>
                    </div>



                    <div id="id_post_type">
                        <div>
                            <label for="id_post_type_0" style="color: white;">
                              <input type="radio" name="post_type" value="1" required="" id="id_post_type_0">Лекция
                            </label>
                        </div>
                        <div>
                            <label for="id_post_type_1" style="color: white;">
                              <input type="radio" name="post_type" value="2" required="" id="id_post_type_1">Практика
                            </label>
                        </div>
                    </div>

                    <button class="form-button" type="submit">Добавить</button>
                </div>
            </div>
        </section>
    </form>

    {% endif %}

</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
function handleFileSelect(evt) {
    var group_photo = evt.target.files;
    var cp = group_photo[0];

    if (!cp.type.match('image.*')) {
        alert("Image only please....");
    }
    var reader = new FileReader();

    reader.onload = (function(theFile) {
        return function(e) {

            var span = document.createElement('span');
            span.innerHTML = ['<img class="thumb" width="350" title="', escape(theFile.name), '" src="', e.target.result, '" />'].join('');
            document.getElementById('output').insertBefore(span, null);
        };
    })(cp);

    reader.readAsDataURL(cp);
}
document.getElementById('id_group_photo').addEventListener('change', handleFileSelect, false);

</script>

{% block javascript %}
<script src="{% static 'courses/js/script.js' %}"></script>
{% endblock %}
</html>

illumail/study_groups/templates/update_group.html
 {% load static %}
<!DOCTYPE html>

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>

    <link rel="stylesheet" href="{% static 'courses/css/learning.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"/>

</head>
<body>


<section class="container" style="word-wrap: break-word; width: 100%;">

    {% include 'nav.html' %}

    {% if request.user.is_authenticated %}

    <h2 align="center" style="width: 100%; color: white; margin-top: 30px;">Изменение учебной группы:</h2>

    <form method="post" style="width: 100%; margin-bottom: 10px; height: 830px;" autocomplete="off">
        {% csrf_token %}
        <section class="form-section">
            <div class="form-box" style="height: 730px;">
                <div class="form-value">
                    <div class="inputbox">
                        <input name="title" class="" required value="{{ group.title }}">
                        <label>Название группы</label>
                    </div>
                    <div class="inputbox">
                        <input name="about_the_group" class="" required value="{{ group.about_the_group }}">
                        <label>Описание группы</label>
                    </div>

                    <p style="color: white;">Изображение группы на данный момент:</p>
                    <p><img src="{{ group.group_photo.url }}" alt="" width="250" height="150"></p>

                    <div class="row" style="color: white;">
                        <label>Фото группы:</label>
                        <input type="file" id="id_group_photo" name="group_photo"/>
                    </div>
                    <br>
                    <div class="row" style="color: white;">
                        <span id="output"></span>
                    </div>

                    <button class="form-button" type="submit">Сохранить изменения</button>
                </div>
            </div>
        </section>
    </form>

    {% endif %}

</section>
</body>
<script type="text/javascript" src="{% static 'courses/js/vanilla-tilt.js' %}"></script>
<script>
function handleFileSelect(evt) {
    var group_photo = evt.target.files;
    var cp = group_photo[0];

    if (!cp.type.match('image.*')) {
        alert("Image only please....");
    }
    var reader = new FileReader();

    reader.onload = (function(theFile) {
        return function(e) {

            var span = document.createElement('span');
            span.innerHTML = ['<img class="thumb" width="350" title="', escape(theFile.name), '" src="', e.target.result, '" />'].join('');
            document.getElementById('output').insertBefore(span, null);
        };
    })(cp);

    reader.readAsDataURL(cp);
}
document.getElementById('id_group_photo').addEventListener('change', handleFileSelect, false);
</script>

{% block javascript %}
<script src="{% static 'courses/js/script.js' %}"></script>
{% endblock %}
</html>